[tool.poetry]
name = "sinar-billwatcher"
version = "0.1.0"
description = ""
authors = ["Chee Leong <cheeleong@tuxuri.com>"]
readme = "README.md"
packages = [{include = "sinar"}]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
